    function loveandMarriage() {
    document.getElementById("themeDesc").innerHTML = "<p> The plot of Sense and Sensibility revolves around marriage. Engagements, possible matches, and marriages are the main concern of most the novel’s characters and the subject of much of their conversation. <br> <br> However, marriage isn’t all about love in the world of Sense and Sensibility. In fact, it’s often more about wealth, uniting families, and gaining social standing. Moreover, it’s often families and parents who organise engagements as much as any individual husband or wife. <br> <br> Marriage was an important part of navigating higher social classes in the early 1800's-- the era of history that Austen herself lived through and thus the world her characters inhabit. It determines who will inherit family fortunes and properties, and is of particular importance to women, whose futures depend almost entirely on the prospects of the men they marry. However, while marriage may often be more a matter of economics than of love, this novel will show us it doesn’t necessarily have to be this way. And, insofar as marriage brings families together and creates new family units, it can create strong and lasting bonds of familial love. </p>";
    document.getElementById("themePhoto").src = "portraits/stand-by.png";
}

    function sensevsSensibility() {
    document.getElementById("themeDesc").innerHTML = "<p>Both Austen’s characters and her narrator spend a great deal of time thinking about people’s character, trying to ascertain and distinguish someone’s particular nature. Austen’s omniscient narrator is generally able to pinpoint exactly what kind of person someone is with exact, often sharply ironic description. It is important for the novel to spend time introducing and describing characters before relating their actions, because—in the world of the novel—people’s inner character is essential for understanding their motives, actions, and desires. <br> <br> Austen’s title offers one important way of understanding someone’s character, based on where they fall on a kind of spectrum between sense and sensibility. Elinor is on the side of sense, while Marianne can be classified as someone more given to sensibility. This means that Elinor is a rational thinker, who values reason and restraint. She doesn’t allow herself to be carried away by emotions. Marianne, by contrast, is a character of extreme emotions. As the narrator says, “Marianne could never love by halves.” She gives herself entirely to her feelings of love, happiness, or despair. Much of the novel demonstrates the follies of excessive sensibility like that of Marianne. It brings her to dangerous extremes of emotion and hysteria. Elinor, meanwhile, is generally admired for her good sense. </p>";
    document.getElementById("themePhoto").src = "portraits/stand-by.png";
}

function elinorProfile() {
    document.getElementById("theBio").innerHTML = "<h3>Elinor Dashwood </h3> <p> Elinor is our protagonist. Back in Austen's time, she would be refered to as our heroine. She is the eldest of Mr. and Mrs. Henry Dashwood's three daughters. Margaret and Marianne are her younger sisters. John Dashwood is her older half-brother, and her late father's only male heir. She is 19-years-old and far more sensible than her sister Marianne. In Chapter 1, the narrator tell us that Elinor “possessed a strength of understanding, and coolness of judgment” in addition to “an excellent heart.” She is trying to stay cool-headed about the loss of their home at Norland Park and be practical about finding a new home. She has been spending a lot of time with Edward Ferrars since he arrived at Norland Park, and her family suspect that he will propose to her soon. </p>";
    document.getElementById("profilePhoto").src = "portraits/elinor_dashwood_portrait.png";
}

function marianneProfile() {
    document.getElementById("theBio").innerHTML = "<h3> Marianne Dashwood </h3> <p> Marianne is the middle daughter of Mr. and Mrs. Henry Dashwood. Elinor Dashwood is her older sister and Margaret is her younger sister. John Dashwood is her half-brother, and her late father's only male heir. She is 17-years-old. In contrast to her sister, she has excessive sensibility, meaning that she is very emotional. When their family loses Norland Park, Marianne openly expresses her grief and unhappiness. Both her and her mother “gave themselves up wholly to their sorrow.” She is also a romantic idealist who is not interested in marrying of money. </p>";
    document.getElementById("profilePhoto").src = "portraits/marianne_dashwood_portrait.png";
}

function edwardProfile() {
    document.getElementById("theBio").innerHTML = "<h3> Edward Ferrars </h3> <p> Edward is the eldest child of Mr and Mrs. Ferrars. Fanny Ferrars is his sister, and she has invited him to Norland Park, the estate that was just inherited by John Dashwood, her husband. He has been spending a lot of time with Elinor Dashwood, who is being forced from the estate by his sister. Unlike his sister, Edward is kind and empathetic, which greatly endears him to the Dashwood sisters and their mother. His family want hom to persue some kind of distinguished career, but he simply desires “domestic comfort” and quiet.</p>";
    document.getElementById("profilePhoto").src = "portraits/edward_ferrars_portrait.png";
}

function fannyProfile() {
    document.getElementById("theBio").innerHTML = "<h3> Fanny Dashwood </h3> <p> Fanny Dashwood, born Fanny Ferrars, in the middle child of Mr. and Mrs. Ferrars. Her older brother is Edward Ferrars, whom she has invited to Norland Park. She is the wife of John Dashwood-- Henry Dashwood's only male heir. They have one son, Harry Dashwood, a young child whom she loves to spoil. Her husband has inherited his late father's estate, Norland Park. She is eager to kick the other Dashwood's from their home at Norland Park and leave them very little income, as she wants all to keep as much as possible for her son. Like her husband, she is  narrow-minded, cold-hearted and selfish. </p>";
    document.getElementById("profilePhoto").src = "portraits/fanny_dashwood_portrait.png";
}

function mrsProfile() {
    document.getElementById("theBio").innerHTML = "<h3> Mrs Dashwood </h3> <p> Write bio later. </p>";
    document.getElementById("profilePhoto").src = "portraits/mrs_dashwood_portrait.png";
}

function johnProfile() {
    document.getElementById("theBio").innerHTML = "<h3> Sir John Middleton </h3> <p> Write a bio later. </p>";
    document.getElementById("profilePhoto").src = "portraits/sir_john_middleton.png";
}

   function chapterOne() {
    document.getElementById("plotDesc").innerHTML = "  <p> We're intoduced to the Dashwood family. In Chapter 1, they are living at Norland Park, a beautiful home at the centre of the expansive Norland estate in Sussex, England. The original owner of the property was a single man. The Dashwood's father, Mr. Henry Dashwood, was his nephew. He invited Henry and his family to come live with him at Norland in order to relieve his lonliness. </p> <p> Henry Dashwood has a son from a previous marriage-- John Dashwood-- and three daughters with his current wife-- Elinor, Marianne and Margaret. </p> <p> John Dashwood has a substantial fortune from his mother’s family, which he increased by marrying into the Ferrars family. Norland Park is worth far more to Henry's three daughters. Their mother has no fortune of her own and their father only has 7,000 pounds to his name. </p> <p>When the owner of Norland Park died, he left his property to Henry Dashwood, but left Henry's current wife and daughter out of the will completely. The terms of the inheritence made it difficult for Henry to put money aside for his family. He had hoped to live a simple life so he could save a portion of the estate's yearly profits for his family, but unfortuantely, Henry became ill and died not long after he inherited the estate.  </p> <p> As Henry's only male heir, ownership of the estate automatically transfered to John. Since he held little affection for his half-sisters, he decided to give them only 1,000 pounds each. Immediately after Henry’s funeral, John’s wife moved into Norland Park without giving Henry’s widow, Mrs. Dashwood, any notice. </p> <p> Mrs. Dashwood was offended by John’s wife Fanny and thought of moving out, but her eldest daughter Elinor persuaded her not to. </p>";
    document.getElementById("plotPhoto").src = "portraits/stand-by.png";
}

    function chapterTwo() {
    document.getElementById("plotDesc").innerHTML = "<p> John’s wife Fanny is now the mistress of Norland, and Mrs. Dashwood and her daughters have become guests in what was once their home. Mrs. Dashwood actually likes the idea remaining at Norland, where everything reminds her of her former happiness with her late husband. </p> <p> Fanny disapproves of John’s plan to give his sisters a total of 3,000 pounds. In her eyes, John is taking away money from their son's inheritence. She thinks that John owes his half-sisters nothing because they aren’t really his sisters. </p> <p> John tells his wife that he can't disobey his fathers dying request, but Fanny says that he did not stipulate that John had to give his sisters money. She persuades him to reduce his gift from 3,000 pounds to 1,500 pounds between the three sisters. In today's England, this would the equivalent of 69,787 pounds. </p> <p> He then proposes that they give Mrs. Dashwood one hundred pounds a year. This would be the equivalent of 4,000 pounds today. Fanny is worried that under such an arrangement, Mrs. Dashwood would live for a long time and they would end up losing a great deal of money. John agrees, and abandons the idea of such an annuity. </p> <p> Fanny says that she thinks Henry probably didn’t even intend for him to give his sisters money, but only wanted him to look out for them. John quickly changes his mind again and decides to give his sisters nothing other than some occasional “neighbourly acts” of kindness. </p>";
    document.getElementById("plotPhoto").src = "portraits/stand-by.png";
}

    function chapterThree() {
    document.getElementById("plotDesc").innerHTML = "<p> Mrs. Dashwood and her daughters have stayed at Norland for several months. They are trying to find a new home. Elinor rejects some possible homes that Mrs. Dashwood liked because they are too expensive. Mrs. Dashwood has learned of John’s promise to his father, and so she is confident that he wil help her and her daughters financially. </p><p> The more Mrs. Dashwood learns of Fanny’s character, the more she dislikes her. However, she doesn't mind living at Norland that much, because of a “growing attachment” between Elinor and Fanny’s brother, Edward Ferrars, who is currently staying at Norland Park while he visits his sister. The narrator notes that some mothers might have been worried about Edward’s fortune, which depended entirely on inheriting from the will of his mother, but Mrs. Dashwood’s only concern is that Elinor and Edward are fond of each other.  </p><p> Edward’s family wants him to seek some kind of distinguished career, but he simply desires “domestic comfort” and quiet. Mrs. Dashwood didn’t take much notice of Edward when he first arrived at Norland, but then Elinor tells her how different he is from Fanny. </p> <p> Mrs. Dashwood thinks that Edward and Elinor will certainly be married soon. She shares her thoughts with Marianne, who laments that Edward lacks any taste in music, art, or books. She concedes, though, that Elinor does not have the same feelings as her, and so perhaps Elinor could be happy with Edward. Marianne then despairs about finding a husband of her own, but her mother assures that she will.</p>";
    document.getElementById("plotPhoto").src = "portraits/stand-by.png";
}